### ISSUE TITLE
Creating asset at path Assets/FacePaint/Resources/FacePaintSettings.asset failed

### ISSUE THREAD

**Issue by tomaszzackiewicz** [SixWays/FacePaint#1]
Hi,
Unity 5.5, Windows 10:
I get these errors:

```
Parent directory must exist before creating asset at Assets/FacePaint/Resources/FacePaintSettings.asset.
UnityEditor.AssetDatabase:CreateAsset(Object, String)
Sigtrap.FacePaint.FacePaint:LoadSettings() (at Assets\FacePaint-master\Editor\FacePaint.cs:263)
Sigtrap.FacePaint.FacePaint:get__settings() (at Assets\FacePaint-master\Editor\FacePaint.cs:274)
Sigtrap.FacePaint.FacePaint:OnEnable() (at Assets\FacePaint-master\Editor\FacePaint.cs:396)
UnityEditorInternal.InternalEditorUtility:LoadSerializedFileAndForget(String)
UnityEditor.WindowLayout:LoadWindowLayout(String, Boolean) (at C:\buildslave\unity\build\Editor\Mono\GUI\WindowLayout.cs:485)

[C:\buildslave\unity\build\Editor/Src/AssetPipeline/AssetInterface.cpp line 2671] 
(Filename: Assets/FacePaint-master/Editor/FacePaint.cs Line: 263)

UnityException: Creating asset at path Assets/FacePaint/Resources/FacePaintSettings.asset failed.
  at (wrapper managed-to-native) UnityEditor.AssetDatabase:CreateAsset (UnityEngine.Object,string)
  at Sigtrap.FacePaint.FacePaint.LoadSettings[FacePaintSettings] () [0x00050] in C:\Users\Tomasz\Documents\Unity Projects\FacePainter\Assets\FacePaint-master\Editor\FacePaint.cs:263 
  at Sigtrap.FacePaint.FacePaint.get__settings () [0x00015] in C:\Users\Tomasz\Documents\Unity Projects\FacePainter\Assets\FacePaint-master\Editor\FacePaint.cs:274 
  at Sigtrap.FacePaint.FacePaint.OnEnable () [0x00146] in C:\Users\Tomasz\Documents\Unity Projects\FacePainter\Assets\FacePaint-master\Editor\FacePaint.cs:396 
UnityEditorInternal.InternalEditorUtility:LoadSerializedFileAndForget(String)
UnityEditor.WindowLayout:LoadWindowLayout(String, Boolean) (at C:\buildslave\unity\build\Editor\Mono\GUI\WindowLayout.cs:485)
 
```

And thousands times the same error in the log file.

**Comment by SixWays** [comment]
Fixed, thanks for the report! It wasn't looking for the right directories if not installed in Assets/FacePaint. Now it dynamically works out what folder you've installed it into and creates the settings assets appropriately. Let me know if it's fixed for you and I'll close the issue.

**Comment by tomaszzackiewicz** [comment]
Thank you - it works now.

Please tell me how to use it. I did what is in Readme.txt file, I have w a Cube and the Face Paint window and now what? I am playing with the properties in the Face Paint windows and nothing. A triangles are only outlines on the Cube.

And other question: Can it work at runtime? I need to pain objects at runtime.

**Comment by SixWays** [comment]
You have to use a shader that supports vertex colours - the standard unity ones mostly don't. If you turn on "assist mode" can you see the colours being painted?

As for runtime - not natively. It should be feasible to adapt parts of the code to work at runtime, but I'm not sure how easy that will be. Plus any painting done at runtime wouldn't be saved; if you wanted persistence with a compiled player you'd have to manually save out the contents of the FacePaintData component somehow.

**Comment by tomaszzackiewicz** [comment]
Ok, I understand how it works now.  I will look into the code to know how to use it at runtime.

Thank a lot for the code.

**Comment by SixWays** [comment]
No problem :)
